name: GNAT

on:
  push:
    branches: [ "dev*", "main", "master" ]
  pull_request:
    branches: [ "dev*", "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up alire
      uses: alire-project/setup-alire@v1
      
    - name: alr build
      run: PRJ_BUILD=Release alr build
