name: GNAT

on:
  push:
    branches: [ "dev*" ]
  pull_request:
    branches: [ "dev*" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install gnat gprbuild
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild

    - name: git clone alire
      run: git clone https://github.com/alire-project/alire.git --recurse-submodules

    - name: build alire
      run: ALIRE_OS=linux gprbuild alire/alr_env.gpr

    - name: gprbuild yass.gpr
      run: gprbuild -j0 -p -Pyass.gpr
